### ISSUE TITLE
Fix dashboard view

### ISSUE THREAD

**Issue by hancush** [datamade/la-metro-dashboard#89]
The dashboard view is currently broken! 🙀

https://la-metro-dashboard.datamade.us/dashboard/

Let's fix this.

**Comment by hancush** [comment]
@antidipyramid Ok, so I cannot reproduce this locally. See if you can use the stack trace in the error on the live site to identify where and why the code is breaking. Leave a short summary of the problem in this issue, and we can chat about how best to resolve.

**Comment by antidipyramid** [comment]
After reading the stack trace, it looks like one of the DAGs is failing at this line in `Dashboard.get_dag_info()`:
<img width="439" alt="Screen Shot 2022-04-14 at 12 46 08 PM" src="https://user-images.githubusercontent.com/36973363/163435752-3242d2e0-c2dc-4f69-9082-b5f35e9027ac.png">

`d.following_schedule()` seems to be returning `None`.  The source for `following_schedule()`:
<img width="809" alt="Screen Shot 2022-04-14 at 12 48 54 PM" src="https://user-images.githubusercontent.com/36973363/163436140-dc876c35-900a-47ad-9ed8-8c16b19636f3.png">

Clearly Airflow wants us to move away from using this function but I'm not sure that that's the problem. I guess the first possibility is that a DAG is returning `None` for `next_dagrun_info()`. 

Did the problem first start when I pushed up the analytics DAG? If so, it's likely that I configured it incorrectly.

**Comment by hancush** [comment]
@antidipyramid Love the instinct to look for the last change (analytics DAG). Unfortunately, this page was broken before that release. It seems like we have a DAG that does not have a next scheduled run. Can you figure out (based on our DAG files) which one doesn't have a schedule? (Hint: This is definitely my fault!!! 😬)

**Comment by antidipyramid** [comment]
Hm, well it seems like the only DAG with no `schedule_interval` is `make_packet.py`. That one is explicitly set to `None`.

If that's it, why can't we reproduce the error locally?

**Comment by hancush** [comment]
@antidipyramid Try running the make_packet DAG in your local instance, then see if the error occurs.

**Comment by antidipyramid** [comment]
@hancush Ah ok, I see now! The Dashboard error doesn't appear until Airflow attempts to run `make_packet`. What do we want to set the interval as?

**Comment by hancush** [comment]
`make_packet` intentionally doesn't have a schedule, because it's triggered by the application. Rather than giving it an interval, I think we need the handle the case where a DAG doesn't have a next scheduled run. Make sense?

**Comment by antidipyramid** [comment]
@hancush Got it. Adding a simple conditional seems to remove the error:
<img width="472" alt="Screen Shot 2022-04-14 at 3 22 10 PM" src="https://user-images.githubusercontent.com/36973363/163461561-3c43ee82-6c5a-462a-839c-d71b706f92d5.png">

I thought this portion of the `templates/dashboard.html` would throw an error for trying to access `pst_time` when `dag.next_scheduled_date` is `None` but it doesn't on my end. I'm thinking of adding an extra check here just in case.
<img width="611" alt="Screen Shot 2022-04-14 at 3 25 35 PM" src="https://user-images.githubusercontent.com/36973363/163462020-a15941cb-c7cd-4d18-8f52-815ce8a5a1f4.png">

**Comment by hancush** [comment]
Interesting, I would expect that, too. I like the idea of a check so it's explicit that there might not be a next run.
